src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    #[ORM\Column(type: 'text')]
    private $contenu;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\ManyToOne(targetEntity: Produit::class, inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private $produit_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getProduitId(): ?Produit
    {
        return $this->produit_id;
    }

    public function setProduitId(?Produit $produit_id): self
    {
        $this->produit_id = $produit_id;

        return $this;
    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    #[ORM\Column(type: 'text')]
    private $description;

    #[ORM\Column(type: 'float')]
    private $prix;

    #[ORM\Column(type: 'string', length: 255)]
    private $image;

    #[ORM\ManyToOne(targetEntity: Categorie::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private $categorie_id;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private $user_id;

    #[ORM\OneToMany(mappedBy: 'produit_id', targetEntity: Commentaire::class)]
    private $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorieId(): ?Categorie
    {
        return $this->categorie_id;
    }

    public function setCategorieId(?Categorie $categorie_id): self
    {
        $this->categorie_id = $categorie_id;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setProduitId($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getProduitId() === $this) {
                $commentaire->setProduitId(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\User;
use App\Entity\Contact;
use App\Entity\Produit;
use App\Entity\Commentaire;
use App\Form\ArticleType;
use App\Form\ContactType;
use App\Form\ProductType;
use App\Form\RechercheType;
use App\Form\CommentaireType;
use App\Notification\ContactNotification;
use App\Repository\ArticleRepository;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\Security;

class SiteController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function home(ProduitRepository $repo, Request $request): Response
    {
        $form = $this->createForm(RechercheType::class);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())    // si on fait une recherche
        {
            $data = $form->get('recherche')->getData(); // je récupère la saisie de l'utilisateur
            $produits = $repo->getProduitsByName($data);
        }
        else    // pas de recherche : on récupère tous les articles
        {
            $produits = $repo->findBy([], ["nom" => "ASC"]);
        }

        return $this->render('site/index.html.twig',[
            'produits' => $produits,
            'formRecherche' => $form->createView()
        ]);
        // pour envoyer des variables à une vue, on les passe dans un tableau associatif
        // indice => valeur
    }

    /**
     * @Route("/show/{id}", name="show_product")
     */
    public function show(Request $request, EntityManagerInterface $manager,Produit $produit = null,Commentaire $commentaire=null)
    {
        $user = $this->getUser();
        $commentaire = new Commentaire;
        $commentaire->setUserId($user);
        $commentaire->setProduitId($produit);
        $commentaire->setCreatedAt(new \DateTime());

        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);
        dump($form);


        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($commentaire);
            $manager->flush();
            return $this->redirectToRoute('show_product',[
                'id' => $produit->getId()
            ]
            );
        }
        if(null === $produit) {
            $this->addFlash("error", "Product Not Found");
            return $this->redirectToRoute("home");
        }else{
        return $this->render('site/show.html.twig',[
            'produit'=> $produit,
            'formCommentaire' => $form->createView()
        ]);
    }
    }

    /**
     * @Route("/profil/{id}", name="user_profil")
     */
    public function showUserProfil(User $user = null)
    {

        if(null === $user) {
            $this->addFlash("error", "User Not Found");
            return $this->redirectToRoute("home");
        }else{
            return $this->render('site/userprofil.html.twig',[
                'user'=> $user
            ]);
        }
    }


    /**
     * @Route("/profil", name="show_profil")
     */
    public function showProfil(ProduitRepository $repo)
    {
        $produits = $repo->findAll();
        return $this->render('site/profil.html.twig',[
            'produits' => $produits,
        ]);
    }

    /**
     * @Route("/new", name="new_product")
     * @Route("/edit/{id}", name="edit_product")
     */
    public function form(Request $request, EntityManagerInterface $manager, Produit $produit=null)
    {
        if(!$produit){
            $user = $this->getUser();
            $produit = new Produit;
            $produit->setUserId($user);
        }
    
        $form = $this->createForm(ProductType::class, $produit);
        $form->handleRequest($request);
        dump($form);
    
        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($produit);
            $manager->flush();
            $this->addFlash('success','Le produit a bien été posté');
            return $this->redirectToRoute('show_product',[
                'id' => $produit->getId()
            ]);
        }
        return $this->render('site/form.html.twig',[
            'editMode' => $produit->getId() !== null,
            'formProduit' => $form->createView()
        ]);
    }

        /**
     * @Route("/contact", name="make_contact")
     */
    public function contact(Request $request, EntityManagerInterface $manager, ContactNotification $cn)
    {
        $contact = new Contact;
        $contact->setCreatedAt(new \DateTime());

        $form = $this->createForm(ContactType::class, $contact);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager->persist($contact);
            $manager->flush();
            $cn->notify($contact);
            $this->addFlash('success', 'Votre message a bien été envoyé !');
            // addFlash() permet de créer des msg de notifications
            // elle prend en param le type et le msg
            return $this->redirectToRoute('make_contact');
            // permet de recharger la page et vider les champs du form
        }
        return $this->render("site/contact.html.twig", [
            'formContact' => $form->createView(),
            'contact' => $contact
        ]);
    }

}
    

templates/site/contact.html.twig
{% extends "base.html.twig" %}

{% block body %}

<h1>
    Nous Contacter
</h1>


{{ form_start(formContact) }}
{# form_widget() permet de gérer un champ d'un formulaire #}
{# form_row() permet de gérer un champ d'un formulaire et son label #}

{{ form_row(formContact.nom, {
    'label': "Nom", 
    'attr': {
        'placeholder': "Entrez vôtre nom de famille"
    }
}) }}

{{ form_row(formContact.prenom, {
    'label': "Prénom",
    'attr': {
        'placeholder': "Entrez vôtre prénom"
    }
}) }}

{{ form_row(formContact.email, {
    'label': "Mail",
    'attr': {
        'placeholder': "Entrez vôtre mail"
    }
}) }}

{{ form_row(formContact.contenu,{
     'label': "Contenu",
    'attr': {
        'placeholder': "Entrez vôtre demande"
    }
}) }}

<button type="submit" class="btn btn-primary">
	<i class="fas fa-share"></i>

{{ form_end(formContact) }}

{% endblock %}

templates/site/form.html.twig
{% extends "base.html.twig" %}

{% block body %}

<h1>
{% if editMode %}
    Modification de l'article
{% else %}
Création d'un article    
{% endif %}
</h1>


{{ form_start(formProduit) }}
{# form_widget() permet de gérer un champ d'un formulaire #}
{# form_row() permet de gérer un champ d'un formulaire et son label #}

{{ form_row(formProduit.nom, {
    'label': "Titre", 
    'attr': {
        'placeholder': "Titre de l'article"
    }
}) }}

{{ form_row(formProduit.description, {
    'label': "Contenu",
    'attr': {
        'placeholder': "Contenu de l'article"
    }
}) }}

{{ form_row(formProduit.prix, {
    'label': "Prix",
    'attr': {
        'placeholder': "Prix en euros"
    }
}) }}

{{ form_row(formProduit.image,{
     'label': "Image",
    'attr': {
        'placeholder': "lien de l'image"
    }
}) }}

{{ form_row(formProduit.categorie_id, {
    label: "Catégorie"
}) }}

<button type="submit" class="btn btn-primary">
{% if editMode %}
Enregistrer les modifications
{% else %}
    Ajouter l'article
{% endif %}
</button>

{{ form_end(formProduit) }}

{% endblock %}

templates/site/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits
{% endblock %}

{% block body %}

{{ form_start(formRecherche) }}

{{ form_widget(formRecherche.recherche, {
	attr: {
		placeholder: "Recherchez un produit"
	}
}) }}

<button type="submit" class="btn btn-primary mt-2">Rechercher</button>
<input type="button" value="Remise à zéro" onClick="location.href=location.href" class="btn btn-primary mt-2" >

{{ form_end(formRecherche) }}

	<h1 class="text-center my-3">Liste des produits</h1>
	<div class="row">

		{% for produit in produits %}

			<div class="col-md-4">
				<div class="card cardindex mb-4" >
					<h3 class="card-header">{{ produit.nom }}</h3>
					<img src="{{ produit.image }}" class="imageindex" alt="Image du produit">
					<p>Publié par {{ produit.userId.username }}</p>
					<p>Catégorie : {{ produit.categorieId.titre }}</p>
					<div class="card body">
						<p class="card-text text-end fw-bold">{{ produit.prix }}$</p>
					</div>
					<div class="card-body text-end">
                    <a href="{{ path('show_product', {id: produit.id}) }}" class="card-link btn">voir</a>
					<a href="{{ path('cart_add', {id: produit.id}) }} " class="card-link btn btn-primary">Ajouter au panier</a>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
{% endblock %}

templates/site/profil.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<section class="row article">
		<article class="card profilcard">
			<h2>Nom d'utilisateur : {{ app.user.username }}
			</h2>
			<div class="content">
			<h2>Email : {{ app.user.email }}
			</h2>
			</div>
		</article>
		<div>
		<h1 class="text-center mx-auto m-3">Produits de {{ app.user.username }} ({{app.user.produits|length}})</h1>
				{% for produit in app.user.produits %}
				<article class="card produitprofil" >

			<h2 class="profilnomproduit"> {{ produit.nom }} </h2>	
			<div class="metadata">
			<div class="content">
				<img src="{{ produit.image }}" class="imageprofil" alt="Image du produit">
				<h3 class="profildescriptionproduit">{{ produit.description|raw }}
				</h3>
                <p class="card-text fw-bold">Prix : {{ produit.prix }}$</p>
				<a href="{{ path('show_product', {id: produit.id}) }}" class="btn btnvoir btn-primary  ">voir</a>
			</div>
		</article>
			{% endfor %}
				<h1 class="text-center mx-auto m-3">Commentaires de {{ app.user.username }} ({{app.user.commentaires|length}})</h1>
	<section id="commentaire" class="col-md-10 mx-auto">
		{% for commentaire in app.user.commentaires %}
			<div class="comment">
				<div class="row">
					<div class="col-md-3">
					<p>produit :{{ commentaire.produitId.nom }}</p>
					<p>commentaire : {{ commentaire.contenu|raw }}</p>
						<p>date : (<small>{{ commentaire.createdAt|date('d/m/Y à H:i:s') }}</small>)</p>
					</div>
				</div>
			</div>
			<hr>
		{% endfor %}
	</section>
		</div>
	</section>
{% endblock %}

templates/site/show.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<section class="row article">
		<article class="card">
			<h2 class="nomproduit">{{ produit.nom }}
			</h2>
			<div class="metadata">
				Catégorie
				{{ produit.categorieId.titre }}</div>
			<div class="content">
				<img src="{{ produit.image }}" class="imageshow" alt="Image du produit">
				<br>
				{{ produit.description|raw }}
                <p class="card-text ">Prix: {{ produit.prix }}$</p>
				<a href="{{ path('cart_add', {id: produit.id}) }} " class="card-link btn btn-primary">Ajouter au panier</a>
				{% if app.user.id == produit.userId.id or is_granted('ROLE_ADMIN')%}
				<a href="{{ path('edit_product', {id: produit.id}) }} " class="card-link btn btn-primary">Modifier le produit</a>
				{% endif %}
			</div>
		</article>
	</section>

	<h2 class="mx-auto m-3">Commentaires</h2>
	<section id="commentaire" class="col-md-10 mx-auto">
		{% for commentaire in produit.commentaires %}
			<div class="comment">
				<div class="row">
					<div class="col-md-3">
					<a href="{{ path('user_profil', {id: commentaire.userId.id}) }}">{{commentaire.userId.username}}</a>
						(<small>{{ commentaire.createdAt|date('d/m/Y à H:i:s') }}</small>)
					</div>
					<div class="col-md-9">
						{{ commentaire.contenu|raw }}
					</div>
				</div>
			</div>
			<hr>
		{% endfor %}
	</section>

	{{ form_start(formCommentaire) }}
	{{ form_row(formCommentaire.contenu, {
    'attr': {
        'placeholder': "Commentaire"
    }
}) }}
	<button type="submit" class="btn btn-primary" label: "Valider">
	<i class="fas fa-share"></i>
	{{ form_end(formCommentaire) }}

{% endblock %}

templates/site/userprofil.html.twig
{% extends "base.html.twig" %}

{% block body %}

	<section class="row article">
		<article class="card profilcard">
			<h2>nom d'utilisateur : {{ user.username }}
			</h2>
			<div class="content">
			<h2>email : {{ user.email }}
			</h2>
			</div>
		</article>
	<div>
		<h1 class="text-center mx-auto m-3">Produits de {{ user.username }} ({{user.produits|length}})</h1>
				{% for produit in user.produits %}
				 						<article class="card produitprofil">
		
			<h2 class="profilnomproduit">{{ produit.nom }}
			</h2>
			<div class="metadata">
			<div class="content">
				<img src="{{ produit.image }}" class="imageprofil" alt="Image du produit">
				<h3 class="profildescriptionproduit">{{ produit.description|raw }}
				</h3>
                <p class="card-text fw-bold">Prix : {{ produit.prix }} $</p>
				<a href="{{ path('show_product', {id: produit.id}) }}" class="btn btnvoir btn-primary">voir</a>
			</div>
		</article>
			{% endfor %}
				<h1 class="text-center mx-auto m-3">Commentaires de {{ user.username }} ({{user.commentaires|length}})</h1>
	<section id="commentaire" class="col-md-10 mx-auto">
		{% for commentaire in user.commentaires %}
			<div class="comment">
				<div class="row">
					<div class="col-md-3">
					<p>produit :{{ commentaire.produitId.nom }}</p>
					<p>commentaire : {{ commentaire.contenu|raw }}</p>
						<p>date : (<small>{{ commentaire.createdAt|date('d/m/Y à H:i:s') }}</small>)</p>
					</div>
				</div>
			</div>
			<hr>
		{% endfor %}
	</section>
		</div>
	</section>
{% endblock %}